name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...

      - name: Staticcheck
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Calculate coverage
        run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
